apiVersion : apps/v1
kind: Deployment
metadata:
  name: "wsdevaks-f2da"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "wsdevaks-f2da"
  template:
    metadata:
      labels:
        app: "wsdevaks-f2da"
    spec:
      containers:
        - name: "wsdevaks-f2da"
          image: "wsdevacr.azurecr.io/wsdevaks"
          ports:
          - containerPort: 5000