apiVersion: v1
kind: Service
metadata:
    name: "wsdevaks-f2da"
    labels:
        app: "wsdevaks-f2da"
spec:
    type: LoadBalancer
    ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
    selector:
        app: "wsdevaks-f2da"